Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
idade,dias:inteiro


Inicio

    dias <- 360
    escreval ("DIgite sua idade a seguir")
    leia (idade)
    
    escreval ("Você já viveu: ",(idade * dias)," anos")



Fimalgoritmo