Algoritmo "Matheus's Calculator"

Var
y,z:real


Inicio
escreval ("Digite um número")
leia (y)
escreval ("Digite um número")
leia (z)
escreval ("O resultado da sua soma é a seguinte:", (y+z))


// ASSIM COMO NOS OUTROS, EXISTEM ESSAS DUAS FORMAS (E TALVEZ MAIS) DE RESOLVER
//ESSA SITUAÇÃO, atribuindo valor a uma variável e descrevendo ela no escreval
//no entanto, esse modo apresentado é muito mais fácil e prático.

Fimalgoritmo