Algoritmo "ABACAXI"

Var
num:inteiro
frase:caracter

Inicio
    escreval ("Digite a frase que você quer se se repita")
    leia (frase)
    
    num <- 1// VARIÁVEL DE CONTROLE
    repita
    
       num <- (num + 1)   //INSTRUÇÕES PARA SE EXECUTAR O CÓDIGO
       escreval (frase)
       
    ate (num > 999)
    
//OBS: Aqui é a mesma coisa que o PARA FAÇA, não precisa necessariamente aplicar
//a repetição, memorize bem.

    


Fimalgoritmo