Algoritmo "abacaxi dos bons"
// Disciplina   : [Linguagem e Lógica de Programação]

Var
v1: vetor [1..4] de inteiro
v2: vetor [1..4] de inteiro
contador:inteiro


Inicio

  para contador de 1 ate 4 faca
  escreval ("Digite um número")
  leia (v1[contador])
  fimpara
  
  para contador de 1 ate 4 faca
  v2 [contador] <- v1 [contador]

  escreval (v2[contador])
  escreval (v1[contador])
  
  fimpara
  
  


Fimalgoritmo